apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <some_name>
  namespace: <namespace>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3

