apiVersion: v1
kind: PersistentVolume
metadata:
  name: <pv name>
  namespace: <pvc_namespace>
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-storage-class
  awsElasticBlockStore:
    volumeID: vol-05e67855b72b42b44
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1b

