apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jwells-stuff
  namespace: jwells
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3

