apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-k-company-eo-company-node-mariadb-galera-1
  namespace: k-company-eo-company
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3

