apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-federation
  namespace: my-namespace
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mariadb-federation
          image: mariadb:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Federation complete"
              echo "More script commands here"
          env: #settings for the script goes here
            - name: MARIADB_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: root-username
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: root-password

