apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-test
  namespace: jw  # Specify the namespace here
spec:
  replicas: 3
  selector:
    matchLabels:
      app: karpenter-test
  template:
    metadata:
      labels:
        app: karpenter-test
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "3600"]

